### ISSUE TITLE
导入时，会突然卡住，然后慢慢又回接着导入，然后又会卡住。

### ISSUE THREAD

**Issue by TrumpBoy** [qiyu/anki_moji#1]
作者您好，我是上次反应问题的anki使用者，我不知道是不是我使用的问题，每次都会更新收藏夹里的单词，然后导入，先开始都很顺利，导入速度很快。
但是，尽管这次您修复了，仍然还有卡顿的现象（三十秒左右导入一个单词，不知道是不是我单词太多了），导致无法出现“成功导入”的提示信息，甚至anki会卡死。 如果可以的话您可以给我一个联系方式吗，以便于我更好的向您反馈。

**Comment by qiyu** [comment]
想问下，你的单词数量是多少？

**Comment by qiyu** [comment]
可以加qq:2570845188

**Comment by TrumpBoy** [comment]
> 可以加qq:2570845188

大概1400 个单词 因为每天都在收集单词
